<number>	::= ([0-9]*)
% Commands Description %

<push>		::= "push" <number>
<pop>		::= "pop"
<add>		::= "add"
<sub>		::= "sub"
<mul>		::= "mul"
<div>		::= "div"
<dup>		::= "dup"

<peek>		::= "peek" <reg-value>
<preg>		::= "preg" <reg-value>
<reg-value>	::= (1 | 2 | 3 | 4)
